// When you've added props to your component,
// pass Storybook's `args` through this story to control it from the addons panel:
//
// ```tsx
// import type { ComponentStory } from '@storybook/react'
//
// export const generated: ComponentStory<typeof GeolocationView> = (args) => {
//   return <GeolocationView {...args} />
// }
// ```
//
// See https://storybook.js.org/docs/react/writing-stories/args.

import type { ComponentMeta } from '@storybook/react'

import GeolocationView from './GeolocationView'

export const generated = () => {
  return <GeolocationView geoLocations={response.data.geoLocationsByZip} />
}

export default {
  title: 'Components/GeolocationView',
  component: GeolocationView,
} as ComponentMeta<typeof GeolocationView>

const response = {
  data: {
    geoLocationsByZip: [
      {
        id: 29266,
        city: 'Alpine',
        county: 'Brewster',
        fips: '48',
        state: 'Texas',
        stateAbbrev: 'TX',
        zip: '79830',
        stations: [
          {
            stationName: 'LOGAN MARTIN DAM',
            longitude: -86.3386,
            latitude: 33.4258,
            hcn: '',
            gsn: '',
            code: 'USC00014866',
            elevation: 137.2,
            id: 'cl99bzdiy005svwx4l08c823a',
            wmoid: '',
            climateEntries: [],
          },
          {
            stationName: 'ALPINE',
            longitude: -109.1469,
            latitude: 33.8492,
            hcn: '',
            gsn: '',
            code: 'USC00020159',
            elevation: 2453.6,
            id: 'cl99bzeni0090vwx4gtxbj85d',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 148,
                stationId: 'cl99bzeni0090vwx4gtxbj85d',
                dataPoints: [
                  {
                    value: '297',
                    label: 'jan',
                    id: 'cl99c65kv0x3evwx4b2a3k3s2',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '325',
                    label: 'feb',
                    id: 'cl99c65kv0x3fvwx4p36zkw39',
                    flag: 'R',
                    climateEntryId: 148,
                  },
                  {
                    value: '368',
                    label: 'mar',
                    id: 'cl99c65kv0x3gvwx4w1hpnwn9',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '425',
                    label: 'apr',
                    id: 'cl99c65kv0x3hvwx4p525upwp',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '495',
                    label: 'may',
                    id: 'cl99c65kv0x3ivwx46u10c340',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '570',
                    label: 'jun',
                    id: 'cl99c65kv0x3jvwx41vvu0kxy',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '616',
                    label: 'jul',
                    id: 'cl99c65kv0x3kvwx4mdpq428m',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '601',
                    label: 'aug',
                    id: 'cl99c65kv0x3lvwx4i1zwrlap',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '546',
                    label: 'sep',
                    id: 'cl99c65kv0x3mvwx4toi8g1ab',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '455',
                    label: 'oct',
                    id: 'cl99c65kv0x3nvwx4h6gqkztw',
                    flag: 'R',
                    climateEntryId: 148,
                  },
                  {
                    value: '368',
                    label: 'nov',
                    id: 'cl99c65kv0x3ovwx4rvegk1k8',
                    flag: 'S',
                    climateEntryId: 148,
                  },
                  {
                    value: '301',
                    label: 'dec',
                    id: 'cl99c65kv0x3pvwx4alx3budb',
                    flag: 'R',
                    climateEntryId: 148,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 7649,
                stationId: 'cl99bzeni0090vwx4gtxbj85d',
                dataPoints: [
                  {
                    value: '144',
                    label: 'jan',
                    id: 'cl99c6tnx4s02vwx4ugodykkj',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '178',
                    label: 'feb',
                    id: 'cl99c6tnx4s03vwx4eg0k4lm5',
                    flag: 'R',
                    climateEntryId: 7649,
                  },
                  {
                    value: '215',
                    label: 'mar',
                    id: 'cl99c6tnx4s04vwx4y7le32wk',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '257',
                    label: 'apr',
                    id: 'cl99c6tnx4s05vwx4s5vb9jv4',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '314',
                    label: 'may',
                    id: 'cl99c6tnx4s06vwx41ncaeeyj',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '375',
                    label: 'jun',
                    id: 'cl99c6tnx4s07vwx4jn57vac7',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '455',
                    label: 'jul',
                    id: 'cl99c6tnx4s08vwx4s5g961qh',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '453',
                    label: 'aug',
                    id: 'cl99c6tnx4s09vwx4jgwioemh',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '385',
                    label: 'sep',
                    id: 'cl99c6tnx4s0avwx4522oqf85',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '291',
                    label: 'oct',
                    id: 'cl99c6tnx4s0bvwx497p2twoe',
                    flag: 'R',
                    climateEntryId: 7649,
                  },
                  {
                    value: '206',
                    label: 'nov',
                    id: 'cl99c6tnx4s0cvwx4q3s4jgra',
                    flag: 'S',
                    climateEntryId: 7649,
                  },
                  {
                    value: '146',
                    label: 'dec',
                    id: 'cl99c6tnx4s0dvwx4tlgoboi2',
                    flag: 'R',
                    climateEntryId: 7649,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 15150,
                stationId: 'cl99bzeni0090vwx4gtxbj85d',
                dataPoints: [
                  {
                    value: '450',
                    label: 'jan',
                    id: 'cl99c7hgk8mwqvwx4m1ahucat',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '472',
                    label: 'feb',
                    id: 'cl99c7hgk8mwrvwx4gmgx3swe',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '521',
                    label: 'mar',
                    id: 'cl99c7hgk8mwsvwx47hejmivw',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '593',
                    label: 'apr',
                    id: 'cl99c7hgk8mwtvwx4s5pyouya',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '677',
                    label: 'may',
                    id: 'cl99c7hgk8mwuvwx4aikps9sd',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '765',
                    label: 'jun',
                    id: 'cl99c7hgk8mwvvwx4ovqtk0xj',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '776',
                    label: 'jul',
                    id: 'cl99c7hgk8mwwvwx4bvel3x0h',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '748',
                    label: 'aug',
                    id: 'cl99c7hgk8mwxvwx414wat026',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '706',
                    label: 'sep',
                    id: 'cl99c7hgk8mwyvwx4be9jq4f1',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '620',
                    label: 'oct',
                    id: 'cl99c7hgk8mwzvwx4v3jm6bi5',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '530',
                    label: 'nov',
                    id: 'cl99c7hgk8mx0vwx4gqerzu2y',
                    flag: 'S',
                    climateEntryId: 15150,
                  },
                  {
                    value: '455',
                    label: 'dec',
                    id: 'cl99c7hgk8mx1vwx4thaioa2e',
                    flag: 'R',
                    climateEntryId: 15150,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'ALPINE',
            longitude: -116.7775,
            latitude: 32.8358,
            hcn: '',
            gsn: '',
            code: 'USC00040136',
            elevation: 516.6,
            id: 'cl99bzlkc00rovwx4kmx8hz2p',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 402,
                stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
                dataPoints: [
                  {
                    value: '541',
                    label: 'jan',
                    id: 'cl99c66eg11sqvwx4nfilh8ms',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '542',
                    label: 'feb',
                    id: 'cl99c66eg11srvwx4krnzysg0',
                    flag: 'S',
                    climateEntryId: 402,
                  },
                  {
                    value: '559',
                    label: 'mar',
                    id: 'cl99c66eg11ssvwx4kvlu713w',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '592',
                    label: 'apr',
                    id: 'cl99c66eg11stvwx4m8pkx4vt',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '632',
                    label: 'may',
                    id: 'cl99c66eg11suvwx4ngoqldxk',
                    flag: 'S',
                    climateEntryId: 402,
                  },
                  {
                    value: '684',
                    label: 'jun',
                    id: 'cl99c66eg11svvwx4h43rwxa6',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '743',
                    label: 'jul',
                    id: 'cl99c66eg11swvwx4wocolr0s',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '757',
                    label: 'aug',
                    id: 'cl99c66eg11sxvwx46e4jff52',
                    flag: 'S',
                    climateEntryId: 402,
                  },
                  {
                    value: '733',
                    label: 'sep',
                    id: 'cl99c66eg11syvwx4e273pcq5',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '665',
                    label: 'oct',
                    id: 'cl99c66eg11szvwx4c1zny84a',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '592',
                    label: 'nov',
                    id: 'cl99c66eg11t0vwx495212yyl',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                  {
                    value: '535',
                    label: 'dec',
                    id: 'cl99c66eg11t1vwx4wv10mxxs',
                    flag: 'R',
                    climateEntryId: 402,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 7903,
                stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
                dataPoints: [
                  {
                    value: '444',
                    label: 'jan',
                    id: 'cl99c6uh24wpevwx4xd815zu5',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '442',
                    label: 'feb',
                    id: 'cl99c6uh24wpfvwx4us6sd8ui',
                    flag: 'S',
                    climateEntryId: 7903,
                  },
                  {
                    value: '456',
                    label: 'mar',
                    id: 'cl99c6uh24wpgvwx45v5nqwi5',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '481',
                    label: 'apr',
                    id: 'cl99c6uh34wphvwx44zcrl5pr',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '519',
                    label: 'may',
                    id: 'cl99c6uh34wpivwx4ztg89j2h',
                    flag: 'S',
                    climateEntryId: 7903,
                  },
                  {
                    value: '562',
                    label: 'jun',
                    id: 'cl99c6uh34wpjvwx4tzhjxkgr',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '620',
                    label: 'jul',
                    id: 'cl99c6uh34wpkvwx4t0xhrvhb',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '636',
                    label: 'aug',
                    id: 'cl99c6uh34wplvwx47laj4bko',
                    flag: 'S',
                    climateEntryId: 7903,
                  },
                  {
                    value: '614',
                    label: 'sep',
                    id: 'cl99c6uh34wpmvwx448clof2v',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '553',
                    label: 'oct',
                    id: 'cl99c6uh34wpnvwx4as1brsru',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '488',
                    label: 'nov',
                    id: 'cl99c6uh34wpovwx4p0n5d15n',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                  {
                    value: '438',
                    label: 'dec',
                    id: 'cl99c6uh34wppvwx4bnm9sgca',
                    flag: 'R',
                    climateEntryId: 7903,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 15404,
                stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
                dataPoints: [
                  {
                    value: '637',
                    label: 'jan',
                    id: 'cl99c7i9f8rm2vwx42fl1w1j5',
                    flag: 'S',
                    climateEntryId: 15404,
                  },
                  {
                    value: '642',
                    label: 'feb',
                    id: 'cl99c7i9f8rm3vwx4e5i8idll',
                    flag: 'S',
                    climateEntryId: 15404,
                  },
                  {
                    value: '661',
                    label: 'mar',
                    id: 'cl99c7i9f8rm4vwx45epygrv6',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '703',
                    label: 'apr',
                    id: 'cl99c7i9f8rm5vwx4i5v7scdd',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '746',
                    label: 'may',
                    id: 'cl99c7i9f8rm6vwx4z4dvjwmh',
                    flag: 'S',
                    climateEntryId: 15404,
                  },
                  {
                    value: '805',
                    label: 'jun',
                    id: 'cl99c7i9f8rm7vwx4lgyphnv0',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '866',
                    label: 'jul',
                    id: 'cl99c7i9f8rm8vwx4pn2fwieq',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '878',
                    label: 'aug',
                    id: 'cl99c7i9f8rm9vwx43w88lgzd',
                    flag: 'S',
                    climateEntryId: 15404,
                  },
                  {
                    value: '851',
                    label: 'sep',
                    id: 'cl99c7i9f8rmavwx4l0o4o0n1',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '776',
                    label: 'oct',
                    id: 'cl99c7i9f8rmbvwx4yw8qreya',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '697',
                    label: 'nov',
                    id: 'cl99c7i9f8rmcvwx45jxna4g7',
                    flag: 'R',
                    climateEntryId: 15404,
                  },
                  {
                    value: '633',
                    label: 'dec',
                    id: 'cl99c7i9f8rmdvwx44ptnrdpw',
                    flag: 'S',
                    climateEntryId: 15404,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'ALPINE',
            longitude: -103.66,
            latitude: 30.3764,
            hcn: 'HCN',
            gsn: '',
            code: 'USC00410174',
            elevation: 1356.4,
            id: 'cl99c3ia90a6uvwx4xsv5mlul',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 4864,
                stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
                dataPoints: [
                  {
                    value: '451',
                    label: 'jan',
                    id: 'cl99c6kne3cfevwx49nda3pjc',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '485',
                    label: 'feb',
                    id: 'cl99c6kne3cffvwx4mpneng0b',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '538',
                    label: 'mar',
                    id: 'cl99c6kne3cfgvwx4iqfrtbj0',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '621',
                    label: 'apr',
                    id: 'cl99c6kne3cfhvwx4tsi02ci4',
                    flag: 'R',
                    climateEntryId: 4864,
                  },
                  {
                    value: '704',
                    label: 'may',
                    id: 'cl99c6kne3cfivwx4ahpxx87q',
                    flag: 'R',
                    climateEntryId: 4864,
                  },
                  {
                    value: '762',
                    label: 'jun',
                    id: 'cl99c6kne3cfjvwx4xu18727s',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '762',
                    label: 'jul',
                    id: 'cl99c6kne3cfkvwx4s6uvcd7j',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '749',
                    label: 'aug',
                    id: 'cl99c6kne3cflvwx4qpi22j29',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '698',
                    label: 'sep',
                    id: 'cl99c6kne3cfmvwx4oll91m6u',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                  {
                    value: '624',
                    label: 'oct',
                    id: 'cl99c6kne3cfnvwx4viemg7s7',
                    flag: 'R',
                    climateEntryId: 4864,
                  },
                  {
                    value: '534',
                    label: 'nov',
                    id: 'cl99c6kne3cfovwx4p6jpkxnm',
                    flag: 'R',
                    climateEntryId: 4864,
                  },
                  {
                    value: '456',
                    label: 'dec',
                    id: 'cl99c6kne3cfpvwx435euwu8y',
                    flag: 'S',
                    climateEntryId: 4864,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12365,
                stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
                dataPoints: [
                  {
                    value: '303',
                    label: 'jan',
                    id: 'cl99c78of77c2vwx4jn42pusq',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '331',
                    label: 'feb',
                    id: 'cl99c78of77c3vwx4qu98jupr',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '379',
                    label: 'mar',
                    id: 'cl99c78of77c4vwx4iflxnydu',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '462',
                    label: 'apr',
                    id: 'cl99c78of77c5vwx4m1m8rwhr',
                    flag: 'R',
                    climateEntryId: 12365,
                  },
                  {
                    value: '554',
                    label: 'may',
                    id: 'cl99c78of77c6vwx49h7999r0',
                    flag: 'R',
                    climateEntryId: 12365,
                  },
                  {
                    value: '623',
                    label: 'jun',
                    id: 'cl99c78of77c7vwx40no38kay',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '639',
                    label: 'jul',
                    id: 'cl99c78of77c8vwx4wl1zuc1o',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '626',
                    label: 'aug',
                    id: 'cl99c78of77c9vwx44um1nlap',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '568',
                    label: 'sep',
                    id: 'cl99c78of77cavwx476icpeun',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                  {
                    value: '481',
                    label: 'oct',
                    id: 'cl99c78of77cbvwx4cp491pl5',
                    flag: 'R',
                    climateEntryId: 12365,
                  },
                  {
                    value: '381',
                    label: 'nov',
                    id: 'cl99c78of77ccvwx4qb4moz0o',
                    flag: 'R',
                    climateEntryId: 12365,
                  },
                  {
                    value: '309',
                    label: 'dec',
                    id: 'cl99c78of77cdvwx4qdzq4fre',
                    flag: 'S',
                    climateEntryId: 12365,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 19866,
                stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
                dataPoints: [
                  {
                    value: '600',
                    label: 'jan',
                    id: 'cl99c7welb28qvwx488gqcr5w',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '639',
                    label: 'feb',
                    id: 'cl99c7welb28rvwx4cv25hdmh',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '696',
                    label: 'mar',
                    id: 'cl99c7welb28svwx41us4vvr1',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '779',
                    label: 'apr',
                    id: 'cl99c7welb28tvwx4kxzvw1ym',
                    flag: 'R',
                    climateEntryId: 19866,
                  },
                  {
                    value: '854',
                    label: 'may',
                    id: 'cl99c7welb28uvwx4itp9kk1j',
                    flag: 'R',
                    climateEntryId: 19866,
                  },
                  {
                    value: '901',
                    label: 'jun',
                    id: 'cl99c7welb28vvwx4imivjkyh',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '885',
                    label: 'jul',
                    id: 'cl99c7welb28wvwx4eigdoxvz',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '871',
                    label: 'aug',
                    id: 'cl99c7welb28xvwx46ajcgr6z',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '828',
                    label: 'sep',
                    id: 'cl99c7welb28yvwx4u3cpm0js',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                  {
                    value: '768',
                    label: 'oct',
                    id: 'cl99c7welb28zvwx4pylr7by4',
                    flag: 'R',
                    climateEntryId: 19866,
                  },
                  {
                    value: '687',
                    label: 'nov',
                    id: 'cl99c7welb290vwx428r5eoh1',
                    flag: 'R',
                    climateEntryId: 19866,
                  },
                  {
                    value: '603',
                    label: 'dec',
                    id: 'cl99c7welb291vwx4dzojl3co',
                    flag: 'S',
                    climateEntryId: 19866,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'LAJITAS',
            longitude: -103.7575,
            latitude: 29.2694,
            hcn: '',
            gsn: '',
            code: 'USC00414950',
            elevation: 732.4,
            id: 'cl99c3r260apevwx4l0clhjyw',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5074,
                stationId: 'cl99c3r260apevwx4l0clhjyw',
                dataPoints: [
                  {
                    value: '509',
                    label: 'jan',
                    id: 'cl99c6lbq3gbevwx40owl83i1',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '560',
                    label: 'feb',
                    id: 'cl99c6lbq3gbfvwx49hlyaz2h',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '635',
                    label: 'mar',
                    id: 'cl99c6lbq3gbgvwx4zn3y0oxq',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '724',
                    label: 'apr',
                    id: 'cl99c6lbq3gbhvwx45ubtnnv7',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '810',
                    label: 'may',
                    id: 'cl99c6lbq3gbivwx4mxwh30gi',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '872',
                    label: 'jun',
                    id: 'cl99c6lbq3gbjvwx4be5weukc',
                    flag: 'C',
                    climateEntryId: 5074,
                  },
                  {
                    value: '871',
                    label: 'jul',
                    id: 'cl99c6lbq3gbkvwx46qz944vz',
                    flag: 'C',
                    climateEntryId: 5074,
                  },
                  {
                    value: '859',
                    label: 'aug',
                    id: 'cl99c6lbq3gblvwx4m7g6oimk',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '811',
                    label: 'sep',
                    id: 'cl99c6lbq3gbmvwx4xn33v3rw',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '720',
                    label: 'oct',
                    id: 'cl99c6lbq3gbnvwx4n96gk6ta',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '601',
                    label: 'nov',
                    id: 'cl99c6lbq3gbovwx4h1xfmvb6',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                  {
                    value: '510',
                    label: 'dec',
                    id: 'cl99c6lbq3gbpvwx4gbs0fdep',
                    flag: 'S',
                    climateEntryId: 5074,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12575,
                stationId: 'cl99c3r260apevwx4l0clhjyw',
                dataPoints: [
                  {
                    value: '331',
                    label: 'jan',
                    id: 'cl99c79b57b82vwx4uqkr0cdo',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '377',
                    label: 'feb',
                    id: 'cl99c79b57b83vwx415qvvfiv',
                    flag: 'C',
                    climateEntryId: 12575,
                  },
                  {
                    value: '447',
                    label: 'mar',
                    id: 'cl99c79b57b84vwx4p6aahznr',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '538',
                    label: 'apr',
                    id: 'cl99c79b57b85vwx4w0x34fbx',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '640',
                    label: 'may',
                    id: 'cl99c79b57b86vwx4b9stunla',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '723',
                    label: 'jun',
                    id: 'cl99c79b57b87vwx4d2vmq0ga',
                    flag: 'C',
                    climateEntryId: 12575,
                  },
                  {
                    value: '736',
                    label: 'jul',
                    id: 'cl99c79b57b88vwx4a2qoqyhd',
                    flag: 'C',
                    climateEntryId: 12575,
                  },
                  {
                    value: '725',
                    label: 'aug',
                    id: 'cl99c79b57b89vwx4sivvyiqb',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '671',
                    label: 'sep',
                    id: 'cl99c79b57b8avwx44ndsldbj',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '557',
                    label: 'oct',
                    id: 'cl99c79b57b8bvwx4lc8fo0yt',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '426',
                    label: 'nov',
                    id: 'cl99c79b57b8cvwx49h6ca6hf',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                  {
                    value: '333',
                    label: 'dec',
                    id: 'cl99c79b57b8dvwx4pzckcbm1',
                    flag: 'S',
                    climateEntryId: 12575,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20076,
                stationId: 'cl99c3r260apevwx4l0clhjyw',
                dataPoints: [
                  {
                    value: '687',
                    label: 'jan',
                    id: 'cl99c7x2mb64qvwx4ieli749n',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '743',
                    label: 'feb',
                    id: 'cl99c7x2mb64rvwx4iu2yu1lm',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '823',
                    label: 'mar',
                    id: 'cl99c7x2mb64svwx4fc36hnk8',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '909',
                    label: 'apr',
                    id: 'cl99c7x2mb64tvwx4tmtt7l76',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '980',
                    label: 'may',
                    id: 'cl99c7x2mb64uvwx433ond6h8',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '1020',
                    label: 'jun',
                    id: 'cl99c7x2mb64vvwx426nvmf3w',
                    flag: 'C',
                    climateEntryId: 20076,
                  },
                  {
                    value: '1005',
                    label: 'jul',
                    id: 'cl99c7x2mb64wvwx4dum5x5w0',
                    flag: 'C',
                    climateEntryId: 20076,
                  },
                  {
                    value: '992',
                    label: 'aug',
                    id: 'cl99c7x2mb64xvwx4tsx3rxz7',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '951',
                    label: 'sep',
                    id: 'cl99c7x2mb64yvwx4dptekdnd',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '883',
                    label: 'oct',
                    id: 'cl99c7x2mb64zvwx4f1luc3ox',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '776',
                    label: 'nov',
                    id: 'cl99c7x2mb650vwx4cjh6ixqm',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                  {
                    value: '687',
                    label: 'dec',
                    id: 'cl99c7x2mb651vwx4flshkw6h',
                    flag: 'S',
                    climateEntryId: 20076,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'STUDY BUTTE',
            longitude: -103.5531,
            latitude: 29.3286,
            hcn: '',
            gsn: '',
            code: 'USC00418714',
            elevation: 781.2,
            id: 'cl99c3x280b32vwx4mwrf5rhd',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5236,
                stationId: 'cl99c3x280b32vwx4mwrf5rhd',
                dataPoints: [
                  {
                    value: '517',
                    label: 'jan',
                    id: 'cl99c6lu93jbevwx46e301fl3',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '569',
                    label: 'feb',
                    id: 'cl99c6lu93jbfvwx4ogjgig63',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '637',
                    label: 'mar',
                    id: 'cl99c6lu93jbgvwx4y0mtrvlw',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '719',
                    label: 'apr',
                    id: 'cl99c6lu93jbhvwx4542tik1z',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '811',
                    label: 'may',
                    id: 'cl99c6lu93jbivwx4c7ya490l',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '861',
                    label: 'jun',
                    id: 'cl99c6lu93jbjvwx4zjnovei8',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '862',
                    label: 'jul',
                    id: 'cl99c6lu93jbkvwx4oy9stuh0',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '854',
                    label: 'aug',
                    id: 'cl99c6lu93jblvwx4nwh3hsxo',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '805',
                    label: 'sep',
                    id: 'cl99c6lu93jbmvwx4vi5jfpf9',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '716',
                    label: 'oct',
                    id: 'cl99c6lu93jbnvwx45f69c49m',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '602',
                    label: 'nov',
                    id: 'cl99c6lu93jbovwx4vcwj3dgz',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                  {
                    value: '514',
                    label: 'dec',
                    id: 'cl99c6lu93jbpvwx4avw3awe5',
                    flag: 'R',
                    climateEntryId: 5236,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12737,
                stationId: 'cl99c3x280b32vwx4mwrf5rhd',
                dataPoints: [
                  {
                    value: '360',
                    label: 'jan',
                    id: 'cl99c79sz7e82vwx4m47fd9tn',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '409',
                    label: 'feb',
                    id: 'cl99c79sz7e83vwx4mgr7lvdr',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '466',
                    label: 'mar',
                    id: 'cl99c79sz7e84vwx4oc8u1l6f',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '547',
                    label: 'apr',
                    id: 'cl99c79t07e85vwx4jqdavef1',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '655',
                    label: 'may',
                    id: 'cl99c79t07e86vwx4156qfq98',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '723',
                    label: 'jun',
                    id: 'cl99c79t07e87vwx4qo85wptb',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '733',
                    label: 'jul',
                    id: 'cl99c79t07e88vwx4d7gksrlt',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '727',
                    label: 'aug',
                    id: 'cl99c79t07e89vwx4us1rlffk',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '671',
                    label: 'sep',
                    id: 'cl99c79t07e8avwx4f9z507c3',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '566',
                    label: 'oct',
                    id: 'cl99c79t07e8bvwx4r7evvi44',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '440',
                    label: 'nov',
                    id: 'cl99c79t07e8cvwx4b3sppb0q',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                  {
                    value: '362',
                    label: 'dec',
                    id: 'cl99c79t07e8dvwx4skecgu5x',
                    flag: 'R',
                    climateEntryId: 12737,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20238,
                stationId: 'cl99c3x280b32vwx4mwrf5rhd',
                dataPoints: [
                  {
                    value: '674',
                    label: 'jan',
                    id: 'cl99c7xl0b94qvwx49l50zmt8',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '729',
                    label: 'feb',
                    id: 'cl99c7xl0b94rvwx49mxqyjoh',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '807',
                    label: 'mar',
                    id: 'cl99c7xl0b94svwx458myjym4',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '890',
                    label: 'apr',
                    id: 'cl99c7xl0b94tvwx4c8cu7pcb',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '967',
                    label: 'may',
                    id: 'cl99c7xl0b94uvwx476ryovj3',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '999',
                    label: 'jun',
                    id: 'cl99c7xl0b94vvwx42e6bwg4k',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '991',
                    label: 'jul',
                    id: 'cl99c7xl0b94wvwx4qx3ocu6p',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '980',
                    label: 'aug',
                    id: 'cl99c7xl0b94xvwx4az1ryukt',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '939',
                    label: 'sep',
                    id: 'cl99c7xl0b94yvwx4c6khy03p',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '867',
                    label: 'oct',
                    id: 'cl99c7xl0b94zvwx4j9f8r94l',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '764',
                    label: 'nov',
                    id: 'cl99c7xl0b950vwx41vfwcfiw',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                  {
                    value: '665',
                    label: 'dec',
                    id: 'cl99c7xl0b951vwx46yrt8ljv',
                    flag: 'R',
                    climateEntryId: 20238,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'TERLINGUA',
            longitude: -103.595,
            latitude: 29.3486,
            hcn: '',
            gsn: '',
            code: 'USC00418924',
            elevation: 802.5,
            id: 'cl99c3xb80b3ovwx4zrjgc4ie',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5243,
                stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
                dataPoints: [
                  {
                    value: '496',
                    label: 'jan',
                    id: 'cl99c6lv33jg2vwx4skwxt3sk',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '548',
                    label: 'feb',
                    id: 'cl99c6lv33jg3vwx4igl1kkuc',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '625',
                    label: 'mar',
                    id: 'cl99c6lv33jg4vwx4gf6jkdee',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '718',
                    label: 'apr',
                    id: 'cl99c6lv33jg5vwx41dhe9ui8',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '807',
                    label: 'may',
                    id: 'cl99c6lv33jg6vwx4l6y7tjt2',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '862',
                    label: 'jun',
                    id: 'cl99c6lv33jg7vwx4iofvewop',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '859',
                    label: 'jul',
                    id: 'cl99c6lv33jg8vwx46waj4lie',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '846',
                    label: 'aug',
                    id: 'cl99c6lv33jg9vwx4verphu45',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '807',
                    label: 'sep',
                    id: 'cl99c6lv33jgavwx4a428winc',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '713',
                    label: 'oct',
                    id: 'cl99c6lv33jgbvwx4b8992v4i',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '592',
                    label: 'nov',
                    id: 'cl99c6lv33jgcvwx4t1ozrcno',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                  {
                    value: '514',
                    label: 'dec',
                    id: 'cl99c6lv33jgdvwx4nrd2gguk',
                    flag: 'Q',
                    climateEntryId: 5243,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12744,
                stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
                dataPoints: [
                  {
                    value: '323',
                    label: 'jan',
                    id: 'cl99c79tr7ecqvwx4wrfk95wi',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '366',
                    label: 'feb',
                    id: 'cl99c79tr7ecrvwx4pcjp9oba',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '439',
                    label: 'mar',
                    id: 'cl99c79tr7ecsvwx4lp2pl95d',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '537',
                    label: 'apr',
                    id: 'cl99c79tr7ectvwx4p793ibl0',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '635',
                    label: 'may',
                    id: 'cl99c79tr7ecuvwx4lzdzna5b',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '707',
                    label: 'jun',
                    id: 'cl99c79tr7ecvvwx4t1401uk9',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '720',
                    label: 'jul',
                    id: 'cl99c79tr7ecwvwx41224yn0f',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '712',
                    label: 'aug',
                    id: 'cl99c79tr7ecxvwx4kmais3ae',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '668',
                    label: 'sep',
                    id: 'cl99c79tr7ecyvwx40tm0vrtg',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '553',
                    label: 'oct',
                    id: 'cl99c79tr7eczvwx44hwv7aps',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '436',
                    label: 'nov',
                    id: 'cl99c79tr7ed0vwx4hmmhkkgu',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                  {
                    value: '349',
                    label: 'dec',
                    id: 'cl99c79tr7ed1vwx4rsuwax0a',
                    flag: 'Q',
                    climateEntryId: 12744,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20245,
                stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
                dataPoints: [
                  {
                    value: '669',
                    label: 'jan',
                    id: 'cl99c7xlrb99evwx45qxyd7mh',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '729',
                    label: 'feb',
                    id: 'cl99c7xlrb99fvwx41qmj1zks',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '811',
                    label: 'mar',
                    id: 'cl99c7xlrb99gvwx4gmtx4ang',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '898',
                    label: 'apr',
                    id: 'cl99c7xlrb99hvwx4oiqv1f1m',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '978',
                    label: 'may',
                    id: 'cl99c7xlrb99ivwx4qpq9qewb',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '1017',
                    label: 'jun',
                    id: 'cl99c7xlrb99jvwx4of0jw61z',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '998',
                    label: 'jul',
                    id: 'cl99c7xlrb99kvwx4us5zitwf',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '980',
                    label: 'aug',
                    id: 'cl99c7xlrb99lvwx4zjhe72nt',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '945',
                    label: 'sep',
                    id: 'cl99c7xlrb99mvwx4lgnyoynb',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '872',
                    label: 'oct',
                    id: 'cl99c7xlrb99nvwx47qguf4il',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '748',
                    label: 'nov',
                    id: 'cl99c7xlrb99ovwx4ilvq3d0r',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                  {
                    value: '679',
                    label: 'dec',
                    id: 'cl99c7xlrb99pvwx4smrmio7c',
                    flag: 'Q',
                    climateEntryId: 20245,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'TERLINGUA RANCH 2',
            longitude: -103.4061,
            latitude: 29.4744,
            hcn: '',
            gsn: '',
            code: 'USC00418926',
            elevation: 1122.3,
            id: 'cl99c3xbv0b3qvwx4gfuz9lyv',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5244,
                stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
                dataPoints: [
                  {
                    value: '484',
                    label: 'jan',
                    id: 'cl99c6lv73jgqvwx4zz0ey72t',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '520',
                    label: 'feb',
                    id: 'cl99c6lv73jgrvwx4h3x0t5x6',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '587',
                    label: 'mar',
                    id: 'cl99c6lv73jgsvwx414tec1bh',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '669',
                    label: 'apr',
                    id: 'cl99c6lv73jgtvwx449y38frs',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '752',
                    label: 'may',
                    id: 'cl99c6lv73jguvwx4cglb2y39',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '802',
                    label: 'jun',
                    id: 'cl99c6lv73jgvvwx44ts6riqp',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '800',
                    label: 'jul',
                    id: 'cl99c6lv73jgwvwx4xom4jnhp',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '790',
                    label: 'aug',
                    id: 'cl99c6lv73jgxvwx4o88lb9du',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '745',
                    label: 'sep',
                    id: 'cl99c6lv73jgyvwx4i0ys5cyr',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '663',
                    label: 'oct',
                    id: 'cl99c6lv73jgzvwx4dqab1af2',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '569',
                    label: 'nov',
                    id: 'cl99c6lv73jh0vwx4xcbj93tl',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                  {
                    value: '487',
                    label: 'dec',
                    id: 'cl99c6lv73jh1vwx42rgksk6v',
                    flag: 'R',
                    climateEntryId: 5244,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12745,
                stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
                dataPoints: [
                  {
                    value: '348',
                    label: 'jan',
                    id: 'cl99c79tu7edevwx426blsyvh',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '372',
                    label: 'feb',
                    id: 'cl99c79tu7edfvwx48c1uu3rs',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '437',
                    label: 'mar',
                    id: 'cl99c79tu7edgvwx4tqwqpen3',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '513',
                    label: 'apr',
                    id: 'cl99c79tu7edhvwx4zklp43yz',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '601',
                    label: 'may',
                    id: 'cl99c79tu7edivwx49qji1f8n',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '661',
                    label: 'jun',
                    id: 'cl99c79tu7edjvwx4os5tulrx',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '669',
                    label: 'jul',
                    id: 'cl99c79tu7edkvwx4d1z5zukp',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '662',
                    label: 'aug',
                    id: 'cl99c79tu7edlvwx4583hkf73',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '615',
                    label: 'sep',
                    id: 'cl99c79tu7edmvwx4zeewxgxd',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '525',
                    label: 'oct',
                    id: 'cl99c79tu7ednvwx4fbc7b59f',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '423',
                    label: 'nov',
                    id: 'cl99c79tu7edovwx4ksb44x3u',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                  {
                    value: '348',
                    label: 'dec',
                    id: 'cl99c79tu7edpvwx4esk0up51',
                    flag: 'R',
                    climateEntryId: 12745,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20246,
                stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
                dataPoints: [
                  {
                    value: '621',
                    label: 'jan',
                    id: 'cl99c7xlvb9a2vwx4ghrsbvwr',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '668',
                    label: 'feb',
                    id: 'cl99c7xlvb9a3vwx4rnm5jbvq',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '738',
                    label: 'mar',
                    id: 'cl99c7xlvb9a4vwx468m2zavu',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '825',
                    label: 'apr',
                    id: 'cl99c7xlvb9a5vwx4mxzwp2xa',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '903',
                    label: 'may',
                    id: 'cl99c7xlvb9a6vwx4mqjeyy8q',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '943',
                    label: 'jun',
                    id: 'cl99c7xlvb9a7vwx4wp7nm9jv',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '932',
                    label: 'jul',
                    id: 'cl99c7xlvb9a8vwx4oz6cwj3d',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '918',
                    label: 'aug',
                    id: 'cl99c7xlvb9a9vwx4kzx2bfns',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '875',
                    label: 'sep',
                    id: 'cl99c7xlvb9aavwx4imrl8790',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '800',
                    label: 'oct',
                    id: 'cl99c7xlvb9abvwx47ct4wspb',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '714',
                    label: 'nov',
                    id: 'cl99c7xlvb9acvwx4llk0j2h1',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                  {
                    value: '626',
                    label: 'dec',
                    id: 'cl99c7xlvb9advwx4ef17m48u',
                    flag: 'R',
                    climateEntryId: 20246,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'ALPINE',
            longitude: -111.7708,
            latitude: 40.4644,
            hcn: '',
            gsn: '',
            code: 'USC00420061',
            elevation: 1545.3,
            id: 'cl99c3yyw0b7evwx46dd478li',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5283,
                stationId: 'cl99c3yyw0b7evwx46dd478li',
                dataPoints: [
                  {
                    value: '289',
                    label: 'jan',
                    id: 'cl99c6lzm3k6qvwx4zwb6ooby',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '332',
                    label: 'feb',
                    id: 'cl99c6lzm3k6rvwx4aeiai9uu',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '420',
                    label: 'mar',
                    id: 'cl99c6lzm3k6svwx4qsssl6we',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '490',
                    label: 'apr',
                    id: 'cl99c6lzm3k6tvwx4v2vd4fth',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '574',
                    label: 'may',
                    id: 'cl99c6lzm3k6uvwx4j931qis1',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '661',
                    label: 'jun',
                    id: 'cl99c6lzm3k6vvwx4jz3w1zkf',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '732',
                    label: 'jul',
                    id: 'cl99c6lzm3k6wvwx446e7ekhz',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '721',
                    label: 'aug',
                    id: 'cl99c6lzm3k6xvwx4bfq4mm6h',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '630',
                    label: 'sep',
                    id: 'cl99c6lzm3k6yvwx4ujrmj6y3',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '513',
                    label: 'oct',
                    id: 'cl99c6lzm3k6zvwx4ke3gnwd0',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '390',
                    label: 'nov',
                    id: 'cl99c6lzm3k70vwx4tujwbefs',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                  {
                    value: '294',
                    label: 'dec',
                    id: 'cl99c6lzm3k71vwx42v0hzvam',
                    flag: 'S',
                    climateEntryId: 5283,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12784,
                stationId: 'cl99c3yyw0b7evwx46dd478li',
                dataPoints: [
                  {
                    value: '204',
                    label: 'jan',
                    id: 'cl99c79y37f3evwx4l3oo8h94',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '236',
                    label: 'feb',
                    id: 'cl99c79y37f3fvwx4jihdps2r',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '309',
                    label: 'mar',
                    id: 'cl99c79y37f3gvwx442gv5zls',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '367',
                    label: 'apr',
                    id: 'cl99c79y37f3hvwx41s4ouvv2',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '435',
                    label: 'may',
                    id: 'cl99c79y37f3ivwx40qhc65aw',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '507',
                    label: 'jun',
                    id: 'cl99c79y37f3jvwx4p436ng7c',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '574',
                    label: 'jul',
                    id: 'cl99c79y37f3kvwx4veo5x2xe',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '569',
                    label: 'aug',
                    id: 'cl99c79y37f3lvwx45abb6lwq',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '479',
                    label: 'sep',
                    id: 'cl99c79y37f3mvwx4p0w9bieb',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '382',
                    label: 'oct',
                    id: 'cl99c79y37f3nvwx471uiqup2',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '290',
                    label: 'nov',
                    id: 'cl99c79y37f3ovwx4s8isbzp1',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                  {
                    value: '212',
                    label: 'dec',
                    id: 'cl99c79y37f3pvwx4sexcs969',
                    flag: 'S',
                    climateEntryId: 12784,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20285,
                stationId: 'cl99c3yyw0b7evwx46dd478li',
                dataPoints: [
                  {
                    value: '374',
                    label: 'jan',
                    id: 'cl99c7xqaba02vwx4wgnp9ntz',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '429',
                    label: 'feb',
                    id: 'cl99c7xqaba03vwx4rzhbszz7',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '530',
                    label: 'mar',
                    id: 'cl99c7xqaba04vwx4zbax2hsh',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '613',
                    label: 'apr',
                    id: 'cl99c7xqaba05vwx4gjihgmlx',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '713',
                    label: 'may',
                    id: 'cl99c7xqaba06vwx4jrseme7c',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '815',
                    label: 'jun',
                    id: 'cl99c7xqaba07vwx4ofv9iqc7',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '890',
                    label: 'jul',
                    id: 'cl99c7xqaba08vwx4kv4p3our',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '873',
                    label: 'aug',
                    id: 'cl99c7xqaba09vwx4kpwy1uc0',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '781',
                    label: 'sep',
                    id: 'cl99c7xqaba0avwx4a9lykwpt',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '645',
                    label: 'oct',
                    id: 'cl99c7xqaba0bvwx445eiy35d',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '489',
                    label: 'nov',
                    id: 'cl99c7xqaba0cvwx4eclqqg5m',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                  {
                    value: '376',
                    label: 'dec',
                    id: 'cl99c7xqaba0dvwx47c3bs9h9',
                    flag: 'S',
                    climateEntryId: 20285,
                  },
                ],
              },
            ],
          },
          {
            stationName: 'TIMPANOGOS CAVE',
            longitude: -111.7075,
            latitude: 40.4447,
            hcn: '',
            gsn: '',
            code: 'USC00428733',
            elevation: 1749.6,
            id: 'cl99c42rz0bg2vwx4ilvg1ghk',
            wmoid: '',
            climateEntries: [
              {
                dataSet: 'noaa-mly-tavg-normal',
                period: '1981-2010',
                topic: 'normal-tavg',
                id: 5428,
                stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
                dataPoints: [
                  {
                    value: '274',
                    label: 'jan',
                    id: 'cl99c6mge3mvevwx4g0xq5bev',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '315',
                    label: 'feb',
                    id: 'cl99c6mge3mvfvwx4iexl1hpv',
                    flag: 'R',
                    climateEntryId: 5428,
                  },
                  {
                    value: '395',
                    label: 'mar',
                    id: 'cl99c6mge3mvgvwx4w8avvlvd',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '468',
                    label: 'apr',
                    id: 'cl99c6mge3mvhvwx4v9rxed8u',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '561',
                    label: 'may',
                    id: 'cl99c6mge3mvivwx4zhre7j1e',
                    flag: 'R',
                    climateEntryId: 5428,
                  },
                  {
                    value: '655',
                    label: 'jun',
                    id: 'cl99c6mge3mvjvwx4ugdwsrba',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '745',
                    label: 'jul',
                    id: 'cl99c6mge3mvkvwx4g12svjs6',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '728',
                    label: 'aug',
                    id: 'cl99c6mge3mvlvwx4xkp0zc2w',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '628',
                    label: 'sep',
                    id: 'cl99c6mge3mvmvwx4x7obb1ak',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '496',
                    label: 'oct',
                    id: 'cl99c6mge3mvnvwx4jm5kabat',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '364',
                    label: 'nov',
                    id: 'cl99c6mge3mvovwx4oru6na2c',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                  {
                    value: '277',
                    label: 'dec',
                    id: 'cl99c6mge3mvpvwx4db1gztob',
                    flag: 'S',
                    climateEntryId: 5428,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmin-normal',
                period: '1981-2010',
                topic: 'normal-tmin',
                id: 12929,
                stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
                dataPoints: [
                  {
                    value: '212',
                    label: 'jan',
                    id: 'cl99c7adx7hs2vwx4tb83slmz',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '238',
                    label: 'feb',
                    id: 'cl99c7adx7hs3vwx4ycmr72w3',
                    flag: 'R',
                    climateEntryId: 12929,
                  },
                  {
                    value: '299',
                    label: 'mar',
                    id: 'cl99c7adx7hs4vwx4xhhh44om',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '355',
                    label: 'apr',
                    id: 'cl99c7adx7hs5vwx4hvuy9ku1',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '432',
                    label: 'may',
                    id: 'cl99c7adx7hs6vwx4fwbf84df',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '509',
                    label: 'jun',
                    id: 'cl99c7adx7hs7vwx4pjkhig2w',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '587',
                    label: 'jul',
                    id: 'cl99c7adx7hs8vwx4dbegipzc',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '574',
                    label: 'aug',
                    id: 'cl99c7adx7hs9vwx409hpfu5k',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '488',
                    label: 'sep',
                    id: 'cl99c7adx7hsavwx4pt6i78dt',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '390',
                    label: 'oct',
                    id: 'cl99c7adx7hsbvwx4zk8c1klj',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '293',
                    label: 'nov',
                    id: 'cl99c7adx7hscvwx4kty1qog5',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                  {
                    value: '218',
                    label: 'dec',
                    id: 'cl99c7adx7hsdvwx478uktqxx',
                    flag: 'S',
                    climateEntryId: 12929,
                  },
                ],
              },
              {
                dataSet: 'noaa-mly-tmax-normal',
                period: '1981-2010',
                topic: 'normal-tmax',
                id: 20430,
                stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
                dataPoints: [
                  {
                    value: '337',
                    label: 'jan',
                    id: 'cl99c7y6cbcoqvwx4qxqz9p2w',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '393',
                    label: 'feb',
                    id: 'cl99c7y6cbcorvwx4uo5qmw7j',
                    flag: 'R',
                    climateEntryId: 20430,
                  },
                  {
                    value: '490',
                    label: 'mar',
                    id: 'cl99c7y6cbcosvwx4fjakhsqe',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '581',
                    label: 'apr',
                    id: 'cl99c7y6cbcotvwx4j8yzcjab',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '689',
                    label: 'may',
                    id: 'cl99c7y6cbcouvwx4s650g53c',
                    flag: 'R',
                    climateEntryId: 20430,
                  },
                  {
                    value: '802',
                    label: 'jun',
                    id: 'cl99c7y6cbcovvwx4dkx1bnqk',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '903',
                    label: 'jul',
                    id: 'cl99c7y6cbcowvwx47kgcgu7f',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '882',
                    label: 'aug',
                    id: 'cl99c7y6cbcoxvwx4sk3rlulp',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '768',
                    label: 'sep',
                    id: 'cl99c7y6cbcoyvwx41qbc0fzg',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '602',
                    label: 'oct',
                    id: 'cl99c7y6cbcozvwx4dvuy2w4n',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '435',
                    label: 'nov',
                    id: 'cl99c7y6cbcp0vwx4q0v3m5n8',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                  {
                    value: '337',
                    label: 'dec',
                    id: 'cl99c7y6cbcp1vwx4bz1cfhfw',
                    flag: 'S',
                    climateEntryId: 20430,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
}
