const response = {
  data: {
    geoLocation: {
      city: 'Alpine',
      county: 'Talladega',
      fips: '1',
      id: 6,
      state: 'Alabama',
      stateAbbrev: 'AL',
      zip: '35014',
      stations: [
        {
          code: 'USC00014866',
          elevation: 137.2,
          gsn: '',
          hcn: '',
          id: 'cl99bzdiy005svwx4l08c823a',
          latitude: 33.4258,
          longitude: -86.3386,
          stationName: 'LOGAN MARTIN DAM',
          wmoid: '',
          climateEntries: [],
        },
        {
          code: 'USC00020159',
          elevation: 2453.6,
          gsn: '',
          hcn: '',
          id: 'cl99bzeni0090vwx4gtxbj85d',
          latitude: 33.8492,
          longitude: -109.1469,
          stationName: 'ALPINE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 148,
              period: '1981-2010',
              stationId: 'cl99bzeni0090vwx4gtxbj85d',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 7649,
              period: '1981-2010',
              stationId: 'cl99bzeni0090vwx4gtxbj85d',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 15150,
              period: '1981-2010',
              stationId: 'cl99bzeni0090vwx4gtxbj85d',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00040136',
          elevation: 516.6,
          gsn: '',
          hcn: '',
          id: 'cl99bzlkc00rovwx4kmx8hz2p',
          latitude: 32.8358,
          longitude: -116.7775,
          stationName: 'ALPINE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 402,
              period: '1981-2010',
              stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 7903,
              period: '1981-2010',
              stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 15404,
              period: '1981-2010',
              stationId: 'cl99bzlkc00rovwx4kmx8hz2p',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00410174',
          elevation: 1356.4,
          gsn: '',
          hcn: 'HCN',
          id: 'cl99c3ia90a6uvwx4xsv5mlul',
          latitude: 30.3764,
          longitude: -103.66,
          stationName: 'ALPINE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 4864,
              period: '1981-2010',
              stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12365,
              period: '1981-2010',
              stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 19866,
              period: '1981-2010',
              stationId: 'cl99c3ia90a6uvwx4xsv5mlul',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00414950',
          elevation: 732.4,
          gsn: '',
          hcn: '',
          id: 'cl99c3r260apevwx4l0clhjyw',
          latitude: 29.2694,
          longitude: -103.7575,
          stationName: 'LAJITAS',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5074,
              period: '1981-2010',
              stationId: 'cl99c3r260apevwx4l0clhjyw',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12575,
              period: '1981-2010',
              stationId: 'cl99c3r260apevwx4l0clhjyw',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20076,
              period: '1981-2010',
              stationId: 'cl99c3r260apevwx4l0clhjyw',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00418714',
          elevation: 781.2,
          gsn: '',
          hcn: '',
          id: 'cl99c3x280b32vwx4mwrf5rhd',
          latitude: 29.3286,
          longitude: -103.5531,
          stationName: 'STUDY BUTTE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5236,
              period: '1981-2010',
              stationId: 'cl99c3x280b32vwx4mwrf5rhd',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12737,
              period: '1981-2010',
              stationId: 'cl99c3x280b32vwx4mwrf5rhd',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20238,
              period: '1981-2010',
              stationId: 'cl99c3x280b32vwx4mwrf5rhd',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00418924',
          elevation: 802.5,
          gsn: '',
          hcn: '',
          id: 'cl99c3xb80b3ovwx4zrjgc4ie',
          latitude: 29.3486,
          longitude: -103.595,
          stationName: 'TERLINGUA',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5243,
              period: '1981-2010',
              stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12744,
              period: '1981-2010',
              stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20245,
              period: '1981-2010',
              stationId: 'cl99c3xb80b3ovwx4zrjgc4ie',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00418926',
          elevation: 1122.3,
          gsn: '',
          hcn: '',
          id: 'cl99c3xbv0b3qvwx4gfuz9lyv',
          latitude: 29.4744,
          longitude: -103.4061,
          stationName: 'TERLINGUA RANCH 2',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5244,
              period: '1981-2010',
              stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12745,
              period: '1981-2010',
              stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20246,
              period: '1981-2010',
              stationId: 'cl99c3xbv0b3qvwx4gfuz9lyv',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00420061',
          elevation: 1545.3,
          gsn: '',
          hcn: '',
          id: 'cl99c3yyw0b7evwx46dd478li',
          latitude: 40.4644,
          longitude: -111.7708,
          stationName: 'ALPINE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5283,
              period: '1981-2010',
              stationId: 'cl99c3yyw0b7evwx46dd478li',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12784,
              period: '1981-2010',
              stationId: 'cl99c3yyw0b7evwx46dd478li',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20285,
              period: '1981-2010',
              stationId: 'cl99c3yyw0b7evwx46dd478li',
              topic: 'normal-tmax',
            },
          ],
        },
        {
          code: 'USC00428733',
          elevation: 1749.6,
          gsn: '',
          hcn: '',
          id: 'cl99c42rz0bg2vwx4ilvg1ghk',
          latitude: 40.4447,
          longitude: -111.7075,
          stationName: 'TIMPANOGOS CAVE',
          wmoid: '',
          climateEntries: [
            {
              dataSet: 'noaa-mly-tavg-normal',
              id: 5428,
              period: '1981-2010',
              stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
              topic: 'normal-tavg',
            },
            {
              dataSet: 'noaa-mly-tmin-normal',
              id: 12929,
              period: '1981-2010',
              stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
              topic: 'normal-tmin',
            },
            {
              dataSet: 'noaa-mly-tmax-normal',
              id: 20430,
              period: '1981-2010',
              stationId: 'cl99c42rz0bg2vwx4ilvg1ghk',
              topic: 'normal-tmax',
            },
          ],
        },
      ],
    },
  },
}

export const standard = (/* vars, { ctx, req } */) => ({
  geoLocation: response.data.geoLocation,
})
